/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sample;

import com.sultanofcardio.iib.errors.ProcessingError;
import com.sultanofcardio.iib.models.JSONArrayMessage;
import com.sultanofcardio.iib.models.JSONObjectMessage;
import com.sultanofcardio.iib.nodes.processing.JSONProcessor;
import org.jetbrains.annotations.NotNull;

public class App extends JSONProcessor {


    public App() {
        super("App");
    }

    @Override
    protected void processArray(@NotNull JSONArrayMessage jsonArrayMessage) throws ProcessingError {

    }

    @Override
    protected void processObject(@NotNull JSONObjectMessage jsonObjectMessage) throws ProcessingError {

    }
}
