/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sample;

import com.sultanofcardio.iib.errors.ProcessingError;
import com.sultanofcardio.iib.models.BlobMessage;
import com.sultanofcardio.iib.models.TextMessage;
import com.sultanofcardio.iib.nodes.processing.BlobProcessor;
import com.sultanofcardio.iib.nodes.processing.TextProcessor;
import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.core.config.Configurator;
import org.jetbrains.annotations.NotNull;

import java.nio.charset.StandardCharsets;

public class BlobApp extends BlobProcessor {

    Logger logger = LogManager.getLogger();


    public BlobApp() {
        super("App");
        Configurator.setLevel(logger.getName(), Level.TRACE);
    }

    @Override
    protected void processBlob(@NotNull BlobMessage blobMessage) throws ProcessingError {
        final String text = new String(blobMessage.getBlob(), StandardCharsets.UTF_8);
        logger.trace("Received BLOB message");
        logger.trace(text);
    }

    @Override
    protected void handleError(@NotNull ProcessingError e) {
        logger.error("", e);
    }
}
