/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sample;

import com.sultanofcardio.iib.errors.ProcessingError;
import com.sultanofcardio.iib.models.JSONArrayMessage;
import com.sultanofcardio.iib.models.JSONObjectMessage;
import com.sultanofcardio.iib.nodes.processing.JSONProcessor;
import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.core.config.Configurator;
import org.jetbrains.annotations.NotNull;

public class JSONApp extends JSONProcessor {

    Logger logger = LogManager.getLogger();


    public JSONApp() {
        super("App");
        Configurator.setLevel(logger.getName(), Level.TRACE);
    }

    @Override
    protected void processArray(@NotNull JSONArrayMessage jsonArrayMessage) throws ProcessingError {
        logger.info("Received JSON message:");
        logger.info(jsonArrayMessage.getJson().toString(4));
        System.out.println("Received JSON message");
        logger.trace("Received JSON message");
        logger.error("Received JSON message");
        System.out.println(jsonArrayMessage.getJson().toString(4));
        logger.trace(jsonArrayMessage.getJson().toString(4));
        logger.error(jsonArrayMessage.getJson().toString(4));
    }

    @Override
    protected void processObject(@NotNull JSONObjectMessage jsonObjectMessage) throws ProcessingError {
        logger.info("Received JSON message:");
        logger.info(jsonObjectMessage.getJson().toString(4));
        System.out.println("Received JSON message");
        logger.trace("Received JSON message");
        logger.error("Received JSON message");
        System.out.println(jsonObjectMessage.getJson().toString(4));
        logger.trace(jsonObjectMessage.getJson().toString(4));
        logger.error(jsonObjectMessage.getJson().toString(4));
    }
}
