/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sample;

import com.sultanofcardio.iib.errors.ProcessingError;
import com.sultanofcardio.iib.models.TextMessage;
import com.sultanofcardio.iib.nodes.processing.TextProcessor;
import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.core.config.Configurator;
import org.jetbrains.annotations.NotNull;

public class TextApp extends TextProcessor {

    Logger logger = LogManager.getLogger();


    public TextApp() {
        super("App");
        Configurator.setLevel(logger.getName(), Level.TRACE);
    }

    @Override
    protected void processText(@NotNull TextMessage textMessage) throws ProcessingError {
        final String output = "Received TEXT message";
        System.out.println(output);
        logger.trace(output);
        logger.error(output);
        System.out.println(textMessage.getText());
        logger.trace(textMessage.getText());
        logger.error(textMessage.getText());
    }

    @Override
    protected void handleError(@NotNull ProcessingError e) {
        logger.error("", e);
    }
}
